export const TR = {
  brand: 'doğumgünüsetim',
  brandDark: 'doğumgünü',
  brandAccent: 'setim',
  nav: {
    themes: 'Temalar',
    categories: 'Kategoriler',
    colors: 'Düz Renkler',
    contact: 'İletişim',
    cart: 'Sepet',
    search: 'Ara',
    admin: 'Yönetim',
  },
  hero: {
    searchPlaceholder: 'Hangi temayı arıyorsun? örn: Unicorn',
    cta: 'Temaları Keşfet',
    buildSet: 'Setini Oluştur',
  },
  filters: {
    girl: 'Kız Çocuk',
    boy: 'Erkek Çocuk',
    baby: '1 Yaş',
    unisex: 'Unisex',
    adult: 'Yetişkin',
  },
  how: {
    title: 'Nasıl Çalışır?',
    step1Title: 'Temanı seç',
    step1: 'Unicorn’dan süper kahramana, partinin ruhunu yakala.',
    step2Title: 'Adetleri sen belirle',
    step2: 'Tabak, bardak, örtü… her ürünü ayrı ayrı seç.',
    step3Title: 'Setin kapına gelsin',
    step3: 'Tek sepette, tek kargoda partin evine gelir.',
  },
  home: {
    allThemes: 'Tüm Temalar',
    shopByCategory: 'Kategoriye göre alışveriş',
    solidColors: 'Düz Renkler',
    loadMore: 'Daha Fazla Göster',
    trustShip: 'Hızlı kargo',
    trustPay: 'Güvenli ödeme',
    trustReturn: 'Kolay iade',
    trustWhatsapp: 'WhatsApp destek',
  },
  theme: {
    buildCta: 'Setini Oluştur',
    partySize: 'Kaç kişilik parti?',
    people8: '8 kişi',
    people16: '16 kişi',
    people24: '24 kişi',
    custom: 'Özel',
    notInSet: 'Sete dahil değil',
    soldOut: 'Tükendi',
    recommended: 'Önerilen',
    included: 'Sete dahil',
    yourSet: 'Setin',
    selectedOf: (selected, total) => `${total} üründen ${selected}’i seçildi`,
    complete: 'Setimi Tamamla',
    update: 'Seti Güncelle',
    reset: 'Seçimleri sıfırla',
    needOne: 'En az bir ürün seçmelisin',
    missingRequired: (name) => `${name} seçmedin, emin misin?`,
    added: (name) => `${name} sepete eklendi 🎉`,
    related: 'Bu temayı sevenler bunlara da baktı',
    faq: 'Sıkça sorulanlar',
  },
  cart: {
    title: 'Sepetim',
    emptyTitle: 'Sepetin henüz boş',
    emptyHint: 'Bir tema seç, setini oluştur, partin başlasın.',
    browse: 'Temalara Göz At',
    continue: 'Alışverişe Devam Et',
    goCart: 'Sepete Git',
    editSet: 'Seti Düzenle',
    removeSet: 'Seti Kaldır',
    removeSetConfirm: 'Bu setin tüm ürünleri sepetten silinsin mi?',
    other: 'Diğer Ürünler',
    products: (n) => `${n} ürün`,
    checkout: 'Siparişi Tamamla',
    summary: 'Sipariş özeti',
    subtotal: 'Ara toplam',
    shipping: 'Kargo',
    freeShipping: 'Ücretsiz',
    freeOver: (amount) => `${amount} üzeri kargo bedava`,
    discount: 'İndirim',
    total: 'Genel toplam',
    coupon: 'İndirim kuponu',
    couponPlaceholder: 'Kupon kodu',
    apply: 'Uygula',
    couponOk: 'Kupon uygulandı',
    couponFail: 'Kupon geçersiz. Dene: PARTI10',
    clear: 'Sepeti boşalt',
    drawerTitle: 'Sepetin',
  },
  product: {
    addToCart: 'Sepete Ekle',
    added: 'Eklendi ✓',
    backToTheme: 'Temaya Dön',
    buildSet: 'Setin Tamamını Oluştur →',
    inSetTitle: (name) => `Bu ürün ${name} Setinde`,
    inSetBody: (name) =>
      `Bu ürün ${name} Seti'nin bir parçası. Tabaktan flamaya tüm ürünleri tek sayfada seç, adetleri kendin belirle.`,
    sku: 'SKU',
    inStock: 'Stokta',
    soldOut: 'Tükendi',
    lastLeft: (n) => `Son ${n} adet`,
    off: (n) => `%${n} İndirim`,
    themeChip: (name) => `${name} Teması`,
    perPiece: (label, price) => `${label} · adet başı ${price}`,
    liveTotal: (total, pieces) => `Toplam: ${total} · ${pieces} adet ürün`,
    notify: 'Gelince haber ver',
    notifySoon: 'Yakında',
    specs: 'Özellikler',
    description: 'Açıklama',
    shipping: 'Kargo & İade',
    related: (name) => `${name} Setinin Diğer Ürünleri`,
    relatedCta: 'Tüm seti tek seferde oluştur',
    home: 'Ana Sayfa',
    alsoIn: 'Bu ürün ayrıca şu setlerde:',
    trustShip: 'Hızlı kargo',
    trustReturn: 'Kolay iade',
  },
  checkout: {
    title: 'Siparişi Tamamla',
    customer: 'İletişim',
    address: 'Teslimat adresi',
    name: 'Ad soyad',
    email: 'E-posta',
    phone: 'Telefon',
    city: 'İl',
    district: 'İlçe',
    line: 'Adres',
    postal: 'Posta kodu',
    note: 'Sipariş notu (isteğe bağlı)',
    submit: 'Siparişi Oluştur',
    paymentNote: 'Ödeme entegrasyonu henüz yok — sipariş kaydı oluşturulur, sonra seninle iletişime geçilir.',
  },
  order: {
    thanks: 'Siparişin alındı!',
    number: 'Sipariş numarası',
    hint: 'Kısa süre içinde seninle iletişime geçeceğiz.',
    backHome: 'Ana sayfaya dön',
  },
  common: {
    loading: 'Yükleniyor…',
    retry: 'Tekrar dene',
    errorTitle: 'Bir şeyler ters gitti',
    empty: 'Burada henüz bir şey yok',
    cancel: 'Vazgeç',
    confirm: 'Onayla',
    save: 'Kaydet',
    delete: 'Sil',
    edit: 'Düzenle',
    add: 'Ekle',
    search: 'Ara',
    close: 'Kapat',
    back: 'Geri',
    notFound: 'Sayfa bulunamadı',
    notFoundHint: 'Aradığın parti başka bir masada olabilir.',
    quantity: 'Adet',
  },
  footer: {
    corporate: 'Kurumsal',
    help: 'Yardım',
    categories: 'Kategoriler',
    contact: 'İletişim',
    about: 'Hakkımızda',
    faq: 'SSS',
    shipping: 'Kargo ve teslimat',
    returns: 'İade ve değişim',
    privacy: 'Gizlilik',
    distance: 'Mesafeli satış sözleşmesi',
    rights: 'Tüm hakları saklıdır.',
  },
  admin: {
    login: 'Yönetici girişi',
    email: 'E-posta',
    password: 'Şifre',
    submit: 'Giriş yap',
    dashboard: 'Özet',
    themes: 'Temalar',
    products: 'Ürünler',
    categories: 'Kategoriler',
    colors: 'Renkler',
    orders: 'Siparişler',
    settings: 'Ayarlar',
    logout: 'Çıkış',
    newTheme: 'Yeni tema',
    newProduct: 'Yeni ürün',
    assign: 'Temaya ürün ata',
  },
  static: {
    aboutTitle: 'Hakkımızda',
    contactTitle: 'İletişim',
    faqTitle: 'Sıkça sorulan sorular',
    shippingTitle: 'Kargo ve teslimat',
    returnsTitle: 'İade ve değişim',
    privacyTitle: 'Gizlilik',
    distanceTitle: 'Mesafeli satış sözleşmesi',
  },
};

export const PARTY_SIZES = [8, 16, 24];
export const PAGE_SIZE = 12;
export const CART_SESSION_KEY = 'cart_session';
export const ADMIN_TOKEN_KEY = 'admin_token';
export const COUPON_HINT = 'PARTI10';
export const MAX_QTY = 99;

export const GENDER_LABELS = {
  kiz: 'Kız',
  erkek: 'Erkek',
  unisex: 'Unisex',
};

export const AGE_LABELS = {
  bebek: 'Bebek',
  cocuk: 'Çocuk',
  yetiskin: 'Yetişkin',
};

export const ORDER_STATUS = {
  pending: 'Beklemede',
  confirmed: 'Onaylandı',
  preparing: 'Hazırlanıyor',
  shipped: 'Kargoda',
  delivered: 'Teslim edildi',
  cancelled: 'İptal',
};
